# Generated by Django 3.2.25 on 2024-05-25 13:15

from django.db import migrations, models
import django.db.models.deletion
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('safe_key', models.CharField(default=purchase.models.generate_safe_key, max_length=200)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer')),
            ],
        ),
    ]
